spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/skola
    username: root
    password: panzer
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties: 
      hibernate: 
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect